(() => {
  const app = document.querySelector('#app');
  const prompts = [
    'Fixed an issue where ___ was incorrectly displayed as a candlestick chart.',
    'Added experimental support for ___ in dark mode.',
    'Resolved a crash caused by rapidly clicking ___.',
    'Deprecated the legacy ___ API. Please migrate before Tuesday.',
    'Improved accessibility when users are emotionally affected by ___.',
    'Known issue: widgets may become sentient after ___.',
    'We have made ___ 37% more collaborative.',
    'The onboarding flow now asks fewer questions about ___.',
    'Performance improvements for users with more than 4,000 ___.',
    'Fixed a rounding error that turned ___ into a taxable event.',
    'The settings screen now remembers your preference for ___.',
    'Removed a confusing button labelled ___. It was not supposed to be there.'
  ];
  const answers = [
    'a suspiciously confident raccoon', 'CSS, but wetter', 'the CEO’s pet lizard',
    '11,000 identical notifications', 'a deeply personal spreadsheet', 'an unexpectedly judgmental tooltip',
    'the concept of weekends', 'a legally distinct space whale', 'a premium apology',
    'three pigeons in a trench coat', 'a badly timed confetti cannon', 'the moon’s privacy policy',
    'a keyboard shortcut nobody can prove exists', 'an alarming amount of hummus', 'a haunted PDF',
    'the user’s third monitor', 'a very small but determined asteroid', 'a calendar invite from 2018',
    'the absence of a product manager', 'a non-consensual team-building exercise', 'a pop-up that knows your full name',
    'an aggressively optimistic loading spinner', 'the ghost of Internet Explorer', 'a 14-hour free trial',
    'the phrase “quick question”', 'a fresh coat of technical debt', 'the office ficus',
    'a plugin called Greg', 'the last clean coffee mug', 'a dropdown with too much confidence',
    'the Wi-Fi password written on a banana', 'some extremely premium whitespace', 'a morally ambiguous checkbox',
    'a timeout with abandonment issues', 'the world’s least helpful chatbot', 'a tiny union of ducks',
    'a spreadsheet that has started setting boundaries', 'one very loud semicolon', 'the snack drawer’s terms of service',
    'a status page written entirely in emojis', 'a CRITICAL bug in the vibes layer', 'a mysterious extra Tuesday'
  ];
  const products = [
    ['PigeonOS', 'operating system for city pigeons'], ['Toastify', 'social network for bread'],
    ['MoonBnB', 'holiday rentals on the Moon'], ['PlantGPT', 'houseplants with strong opinions'],
    ['Moustache Maps', 'navigation by facial hair'], ['DogDash', 'same-day delivery for dogs'],
    ['CaveCloud', 'secure storage for prehistoric files'], ['GossipGrid', 'enterprise rumours, responsibly managed']
  ];
  let state = { mode: 'setup', players: [], round: 1, total: 8, seed: '', selected: null, submissions: [], revealed: false, winner: null, seconds: 45, timer: null, scores: {} };

  function hash(text) { let h = 2166136261; for (let i = 0; i < text.length; i++) h = Math.imul(h ^ text.charCodeAt(i), 16777619); return h >>> 0; }
  function seeded(seed) { let x = hash(seed); return () => (x = (x * 1664525 + 1013904223) >>> 0) / 4294967296; }
  function shuffle(list, seed) { const r = seeded(seed); const copy = [...list]; for (let i = copy.length - 1; i > 0; i--) { const j = Math.floor(r() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; }
  function roundData(round = state.round) { const r = seeded(`${state.seed}:round:${round}`); return { prompt: prompts[Math.floor(r() * prompts.length)], product: products[Math.floor(r() * products.length)] }; }
  function hand(name, round) { return shuffle(answers, `${state.seed}:${name.trim().toLowerCase()}:${round}`).slice(0, 7); }
  function esc(value) { return String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c])); }
  function toast(message) { const node = document.querySelector('#toast-template').content.firstElementChild.cloneNode(true); node.textContent = message; document.body.append(node); setTimeout(() => node.remove(), 2600); }
  function copy(text) { navigator.clipboard?.writeText(text).then(() => toast('Copied — send it privately to the host.')).catch(() => toast('Copy the submission code manually.')); }
  function header(right = '') { return `<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">v∞</span> Patch Notes From Another Universe</div>${right}</header>`; }
  function renderSetup() {
    clearInterval(state.timer); app.innerHTML = `${header()}<section class="intro"><div class="eyebrow">A 45-second release-note party game</div><h1>Ship nonsense.<br><span>Win glory.</span></h1><p class="lead">A rotating judge chooses the funniest fake release note. It runs from a single browser, with private player hands sent through your normal meeting chat.</p><div class="setup"><form class="panel" id="setup-form"><h2>Start a room</h2><p>Set up your host screen. Players use the join link to receive a private, deterministic hand of cards.</p><label for="names">Player names</label><input id="names" required placeholder="Aisha, Ben, Carmen, Dato" value="Aisha, Ben, Carmen, Dato" /><div class="form-row"><div><label for="rounds">Rounds</label><select id="rounds"><option value="6">6 quick rounds</option><option value="8" selected>8 rounds</option><option value="12">12 rounds</option></select></div><div><label for="seconds">Pick time</label><select id="seconds"><option value="30">30 seconds</option><option value="45" selected>45 seconds</option><option value="60">60 seconds</option></select></div></div><label class="check"><input id="warm" type="checkbox" checked /> Keep it workplace-friendly-ish</label><button class="primary" type="submit">Open the release train →</button></form><aside class="panel"><h2>How it plays</h2><div class="steps"><div class="step"><div><strong>Host shares this screen</strong>Show the fake app and release-note prompt.</div></div><div class="step"><div><strong>Players open their private hand</strong>They choose a card and privately send its number to the host.</div></div><div class="step"><div><strong>Reveal and judge</strong>Read the entries aloud. The round’s judge picks their favourite.</div></div></div></aside></div></section></div>`;
    document.querySelector('#setup-form').addEventListener('submit', event => { event.preventDefault(); const names = document.querySelector('#names').value.split(',').map(x => x.trim()).filter(Boolean); if (names.length < 3) return toast('Add at least three players.'); state = { ...state, mode: 'host', players: names, total: +document.querySelector('#rounds').value, seconds: +document.querySelector('#seconds').value, seed: Math.random().toString(36).slice(2, 8).toUpperCase(), round: 1, submissions: [], scores: Object.fromEntries(names.map(n => [n, 0])) }; renderHost(); });
  }
  function startTimer() { clearInterval(state.timer); state.remaining = state.seconds; const label = document.querySelector('#timer-value'); if (!label) return; label.textContent = `0:${String(state.remaining).padStart(2, '0')}`; state.timer = setInterval(() => { state.remaining -= 1; if (label) label.textContent = `0:${String(Math.max(0, state.remaining)).padStart(2, '0')}`; if (state.remaining <= 0) { clearInterval(state.timer); toast('Time! Ask for any last card numbers.'); } }, 1000); }
  function hostUrl() { return `${location.href.split('#')[0]}#join=${encodeURIComponent(state.seed)}&round=${state.round}`; }
  function renderHost() {
    const data = roundData(); const judge = state.players[(state.round - 1) % state.players.length]; const chooseOptions = state.players.map(p => `<option value="${esc(p)}">${esc(p)}</option>`).join(''); const submissionCards = state.submissions.map((s, i) => `<article class="submission ${state.winner === i ? 'winner' : ''}"><span class="who">${esc(s.player)} ${state.winner === i ? '• winner' : ''}</span><span class="${state.revealed ? '' : 'hidden'}">${state.revealed ? esc(s.answer) : 'Submission locked'}</span></article>`).join('');
    app.innerHTML = `${header(`<button class="ghost" id="new-game">New room</button>`)}<section class="round-grid"><div><div class="round-meta"><span class="pill">ROUND ${state.round} / ${state.total}</span><span class="product">${esc(data.product[0])} · ${esc(data.product[1])}</span></div><article class="prompt-card"><span class="eyebrow">${esc(data.product[0])} v${Math.floor(hash(state.seed + state.round) % 8) + 1}.${Math.floor(hash('v' + state.round) % 10)}.0</span><p class="prompt">${esc(data.prompt).replace('___', '<span class="blank">___</span>')}</p></article></div><aside class="sidebar"><section class="timer"><strong id="timer-value">0:${String(state.seconds).padStart(2,'0')}</strong><small>SUBMIT BY CHAT</small></section><section class="room-card"><h3>Player join link</h3><p>Share this link, then privately receive each player’s card number in your meeting chat.</p><div class="room-code">${state.seed}</div><button class="secondary" id="copy-link">Copy join link</button></section><section class="room-card"><h3>Round judge</h3><p><strong>${esc(judge)}</strong> chooses their favourite after the reveal.</p></section></aside></section><section class="hands"><div class="hands-title"><h2>Host preview hand</h2><span class="mono">Not for players’ eyes</span></div><div class="cards">${hand('host-preview', state.round).map((card, i) => `<button class="card ${state.selected === i ? 'selected' : ''}" data-host-card="${i}">${esc(card)}<span class="index">${i + 1}</span></button>`).join('')}</div></section><section class="host-stage"><h2>Collect submissions</h2><p>When a player privately sends a card number, add it here. Their exact hand is recreated from their name, room code, and round.</p><form class="submission-form" id="submission-form"><select id="submission-player">${chooseOptions}</select><input id="submission-card" type="number" min="1" max="7" placeholder="Card #" required /><button class="secondary">Add submission</button></form><div class="submissions">${submissionCards || '<div class="notice">No submissions yet. Players open the join link, choose a card, and send the number to you privately.</div>'}</div><div class="host-actions"><button class="secondary" id="reveal">${state.revealed ? 'Hide answers' : 'Reveal answers'}</button><button class="secondary" id="choose-winner" ${!state.revealed || !state.submissions.length ? 'disabled' : ''}>Choose a winner</button><button class="primary" id="next-round" ${state.winner === null ? 'disabled' : ''}>${state.round === state.total ? 'Finish release train' : 'Next release note →'}</button></div><div class="scoreboard" style="margin-top:16px">${Object.entries(state.scores).map(([name, score]) => `<span class="score">${esc(name)} <b>${score}</b></span>`).join('')}</div></section></div>`;
    document.querySelector('#new-game').onclick = renderSetup; document.querySelector('#copy-link').onclick = () => copy(hostUrl()); document.querySelector('#reveal').onclick = () => { state.revealed = !state.revealed; renderHost(); }; document.querySelector('#choose-winner').onclick = chooseWinner; document.querySelector('#next-round').onclick = nextRound;
    document.querySelector('#submission-form').onsubmit = event => { event.preventDefault(); const player = document.querySelector('#submission-player').value; const card = +document.querySelector('#submission-card').value; if (state.submissions.some(s => s.player === player)) return toast(`${player} already has a submission.`); if (!(card >= 1 && card <= 7)) return toast('Use a card number from 1 to 7.'); state.submissions.push({ player, answer: hand(player, state.round)[card - 1] }); state.revealed = false; renderHost(); };
    startTimer();
  }
  function chooseWinner() { const choices = state.submissions.map((s, i) => `${i + 1}. ${s.player} — ${s.answer}`).join('\n'); const picked = window.prompt(`Judge’s choice — enter the submission number:\n\n${choices}`); const index = Number(picked) - 1; if (!Number.isInteger(index) || !state.submissions[index]) return; state.winner = index; state.scores[state.submissions[index].player] += 1; renderHost(); }
  function nextRound() { if (state.round >= state.total) return renderFinal(); state.round += 1; state.submissions = []; state.revealed = false; state.winner = null; renderHost(); }
  function renderFinal() { clearInterval(state.timer); const winners = Object.entries(state.scores).sort((a,b) => b[1] - a[1]); const top = winners[0][1]; app.innerHTML = `${header(`<button class="secondary" id="again">Play again</button>`)}<section class="intro"><div class="eyebrow">Release train complete</div><h1>Version shipped.<br><span>Reality not.</span></h1><p class="lead">The changelog survived. Barely.</p><div class="panel" style="margin-top:32px"><h2>Final standings</h2><div class="scoreboard" style="margin-top:18px">${winners.map(([name, score]) => `<span class="score">${score === top ? '★ ' : ''}${esc(name)} <b>${score}</b></span>`).join('')}</div><p style="margin-top:24px">Start another room for a fresh deck and a new sequence of fake products.</p></div></section></div>`; document.querySelector('#again').onclick = renderSetup; }
  function renderPlayer(seed, round) {
    const dataSeed = seed || ''; const playerState = { seed: dataSeed, round: Number(round) || 1, selected: null, name: '' }; const draw = () => { const data = (() => { const r = seeded(`${playerState.seed}:round:${playerState.round}`); return { prompt: prompts[Math.floor(r()*prompts.length)], product: products[Math.floor(r()*products.length)] }; })(); const cards = playerState.name ? shuffle(answers, `${playerState.seed}:${playerState.name.trim().toLowerCase()}:${playerState.round}`).slice(0,7) : []; app.innerHTML = `${header(`<span class="pill">PLAYER HAND</span>`)}<section class="player-shell"><div class="eyebrow">Room ${esc(playerState.seed)} · Round ${playerState.round}</div><div class="player-prompt">${esc(data.prompt).replace('___', '<span class="blank">___</span>')}</div>${!playerState.name ? `<section class="panel"><h2>Receive your hand</h2><p>Enter your name exactly as the host entered it, then choose one answer card.</p><label for="player-name">Your name</label><input id="player-name" autofocus placeholder="Your name" /><button class="primary" id="deal" style="margin-top:16px">Deal my cards</button></section>` : `<section class="hands"><div class="hands-title"><h2>Your private hand</h2><span class="mono">Pick one card</span></div><div class="cards">${cards.map((card,i) => `<button class="card ${playerState.selected === i ? 'selected' : ''}" data-player-card="${i}">${esc(card)}<span class="index">${i+1}</span></button>`).join('')}</div>${playerState.selected !== null ? `<section class="submission-code"><h2>Send this privately to the host</h2><p>Use the meeting chat or direct message. Do not reveal the card text.</p><code>ROUND ${playerState.round} · ${playerState.name} · CARD ${playerState.selected + 1}</code><button class="primary" id="copy-submission">Copy submission</button></section>` : ''}</section>`}</section></div>`; if (!playerState.name) { document.querySelector('#deal').onclick = () => { playerState.name = document.querySelector('#player-name').value.trim(); if (!playerState.name) return toast('Enter the name your host is using.'); draw(); }; } else { document.querySelectorAll('[data-player-card]').forEach(card => card.onclick = () => { playerState.selected = Number(card.dataset.playerCard); draw(); }); document.querySelector('#copy-submission')?.addEventListener('click', () => copy(`ROUND ${playerState.round} · ${playerState.name} · CARD ${playerState.selected + 1}`)); } }; draw(); }
  function route() { const params = new URLSearchParams(location.hash.replace(/^#/, '')); if (params.has('join')) renderPlayer(params.get('join'), params.get('round')); else renderSetup(); }
  route();
})();
